Feat: create placeholder for empty subfolders
isomerpages/isomercms-backend pull request #137
Opened 2021-03-23 03:41 UTC by alexanderleegs

This PR adds functionality for adding empty subfolders into the CMS, as well as the associated changes required. To be reviewed in conjunction with PR #TBD on the isomercms frontend repo. A discussion of the reasoning behind this change can be found [here](https://docs.google.com/document/d/1EccpS_ATrfOe4DmU4ChXtU9kV6Jl1rFOdKqBLyG6ym8/edit#).

This PR introduces the following changes:

- The automatic deletion of empty folders, subfolders, and resources has been removed, in line with the ability to create empty folders.
- A new Subfolder class has been created for easier creation and management of subfolders, to automatically update the collection.yml file and handle placeholder file creation.
- An additional check for the existence of the resource category directory has been added when retrieving resource pages. This is to distinguish between empty categories and non-existent ones.

2021-03-23 10:30 UTC, kwajiehao requested changes
Left comments. LGTM overall

As discussed offline, we will be refactoring the `create` methods for the `Collection` and `Subfolder` classes so that file-moving is part of the folder/subfolder creation process, instead of the other way around. More details can be found in the CMS working doc [here](https://docs.google.com/document/d/1br6T6wVX0KrcA3nwQEo7OhUrcT4veLnaz0vByEXjVvo/edit#heading=h.oe6c2lk9ggso)

2021-03-24 03:22 UTC, alexanderleegs commented on routes/collections.js
> +    if (!subfolders.includes(targetSubfolderName)) IsomerSubfolder.create(targetSubfolderName)
Good catch, resolved in https://github.com/isomerpages/isomercms-backend/pull/137/commits/8f4525f5f3a60f40b93175dd7ba281c0e302c922

2021-03-24 04:05 UTC, gweiying approved these changes
lgtm

2021-03-24 06:13 UTC, kwajiehao approved these changes
lgtm!

2021-03-25 05:18 UTC, merged