Feat/move resources
isomerpages/isomercms-backend pull request #139
Opened 2021-03-23 10:39 UTC by gweiying

This PR adds an endpoint for moving resources from one resource room to another. Similar to the move endpoints for collection pages and pages, it takes in an array of files and iteratively deletes and creates new files.

2021-03-24 06:55 UTC, kwajiehao commented
As discussed offline, since there are no use cases for bulk movement of resource pages between resource categories, we will be modifying this feature to move only single resource pages from one category to another

2021-03-25 06:16 UTC, kwajiehao requested changes
Typo in route params

2021-03-25 06:52 UTC, gweiying commented on middleware/auth.js
> +auth.post('/v1/sites/:siteName/resources/:resourceRoomName/move/:newResourceRoomName', verifyJwt)
good catch, fixed here

2021-03-25 06:59 UTC, kwajiehao approved these changes
LGTM!

2021-03-31 05:22 UTC, merged