Feat: update config for collections on adding and deleting pages
isomerpages/isomercms-backend pull request #73
Opened 2020-11-12 07:44 UTC by alexanderleegs

This PR resolves https://github.com/isomerpages/isomercms-backend/issues/72. It accomplishes 2 things:
- First, when creating new collectionPages, it automatically generates a new collection and updates the config file
- Second, when deleting collectionPages, it checks if the collection is now empty and removes the collection from the config file if so

2020-11-15 22:00 UTC, kwajiehao requested changes
left comments

2020-11-16 01:35 UTC, alexanderleegs commented on classes/Collection.js
> +			}
Fixed by converting all tabs to spaces in https://github.com/isomerpages/isomercms-backend/pull/73/commits/364ce767cfb59eb6d0c8fbff0dac8db00415faa1

2020-11-16 01:35 UTC, alexanderleegs commented on routes/collectionPages.js
> +    IsomerCollection.create(collectionName)
Resolved in https://github.com/isomerpages/isomercms-backend/pull/73/commits/b65579025ff97360208b6a9a6b3756b41281e1db

2020-11-16 08:39 UTC, kwajiehao approved these changes
Lgtm

2020-11-16 10:13 UTC, merged